name: Checklist

on:
  pull_request:
    types:
      - synchronize
      - opened
      - edited
      - reopened

jobs:
  checklist:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Check if checklist is complete
        run: |
          checklist_file="PULL_REQUEST_TEMPLATE.md"
          pr_number=$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")

          pr_body=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
              "https://api.github.com/repos/${{ github.repository }}/pulls/$pr_number" | jq -r .body)

          echo "pr_number $pr_number"
          echo "pr_body $ pr_body"
          
          if [[ ! "$pr_body" =~ \[x\] ]]; then
            echo "::error file=${checklist_file},line=1::Checklist not completed!"
            exit 1
          fi
